name: Python CI

on: [push]

jobs:
  test:
    name: Run pytest and flake8
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8.15

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8.15
        environment-file: environment.yml
        activate-environment: fastapi
        auto-activate-base: false
        miniconda-version: "latest"

    - name: Install Dependencies
      run: |
        conda env update --file environment.yml --prune

    - name: Check active environment
      run: |
        conda info --envs

    - name: Install flake8
      run: |
        conda run -n fastapi pip install flake8

    - name: Lint with flake8
      run: |
        conda run -n fastapi flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --ignore=E501

    - name: Run tests with pytest
      run: |
        conda run -n fastapi pytest
